src/MoneyTrack.V3/Models/DataAccess/Entities/Category.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace CloudyWing.MoneyTrack.Models.DataAccess.Entities {
    [Table("Categories")]
    public class Category {
        [Key]
        public long Id { get; set; }

        public string Name { get; set; }

        public long DisplayOrder { get; set; }
    }
}

src/MoneyTrack.V3/Pages/Categories/Edit.cshtml.cs
using CloudyWing.MoneyTrack.Infrastructure.Util;
using CloudyWing.MoneyTrack.Models.Application;
using CloudyWing.MoneyTrack.Pages.Categories.Models;
using Microsoft.AspNetCore.Mvc;

namespace CloudyWing.MoneyTrack.Pages.Categories {
    public class EditModel : PageModelBase {
        private readonly CategoryEditAppService appService;

        public EditModel(CategoryEditAppService appService) {
            ExceptionUtils.ThrowIfNull(() => appService);

            this.appService = appService;
        }

        public override string? MenuKey => "Categories";

        [BindProperty]
        public EditInputModel Input { get; set; }

        public async Task OnGetAsync(long? id) {
            Input = id.HasValue
                ? await appService.GetSingleAsync(id.Value)
                : new EditInputModel();
        }

        public async Task<ActionResult> OnPostAsync() {
            ApplicationResult result = await appService.SaveAsync(Input);
            if (result.IsError) {
                StatusNotification = new NotificationViewModel(result);
                return Page();
            }

            return RedirectToPage("./Index");
        }
    }
}

src/MoneyTrack.V3/Pages/Categories/Index.cshtml.cs
using System.ComponentModel.DataAnnotations;
using CloudyWing.MoneyTrack.Infrastructure.Filters;
using CloudyWing.MoneyTrack.Infrastructure.Util;
using CloudyWing.MoneyTrack.Models.Application;
using CloudyWing.MoneyTrack.Pages.Categories.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;

namespace CloudyWing.MoneyTrack.Pages.Categories {
    public class IndexModel : PageModelBase {
        private readonly CategoryIndexAppService appService;

        public IndexModel(CategoryIndexAppService appService) {
            ExceptionUtils.ThrowIfNull(() => appService);

            this.appService = appService;
        }

        public override string? MenuKey => "Categories";

        [BindProperty]
        public IndexInputModel? Input { get; set; }

        [BindProperty]
        public IEnumerable<IndexRecordModel>? Records { get; set; }

        public async Task OnGetAsync() {
            Input = GetInternalTempData(nameof(IndexInputModel), () => new IndexInputModel(), true);
            Records = await appService.GetListAsync(Input);
        }

        [ValidationExecution(OnFailResultAction = nameof(LoadPrevRecordsAsync))]
        public async Task OnPostAsync(int pageNumber = 1) {
            Input!.PageNumber = pageNumber;
            Records = await appService.GetListAsync(Input);

            SetInternalTempData(nameof(IndexInputModel), Input);
        }

        [ValidationExecution(OnFailResultAction = nameof(LoadPrevRecordsAsync))]
        public async Task<IActionResult> OnPostMoveUpAsync([BindRequired] long id) {
            return await OnPostInternalAsync(() => appService.MoveUpAsync(id));
        }

        private async Task<IActionResult> OnPostInternalAsync(Func<Task<ApplicationResult>> handlerAsync) {
            ApplicationResult result = await handlerAsync();
            StatusNotification = new NotificationViewModel(result);

            if (result.IsError) {
                await LoadPrevRecordsAsync();
                return Page();
            }

            return RedirectToPage("Index");
        }

        [ValidationExecution(OnFailResultAction = nameof(LoadPrevRecordsAsync))]
        public async Task<IActionResult> OnPostMoveDownAsync([BindRequired] long id) {
            return await OnPostInternalAsync(() => appService.MoveDownAsync(id));
        }

        [ValidationExecution(OnFailResultAction = nameof(LoadPrevRecordsAsync))]
        public async Task<IActionResult> OnPostDeleteAsync([BindRequired] long id) {
            return await OnPostInternalAsync(() => appService.DeleteAsync(id));
        }

        private async Task LoadPrevRecordsAsync() {
            IndexInputModel? prevInput = GetInternalTempData(nameof(IndexInputModel), () => new IndexInputModel(), true);
            Records = await appService.GetListAsync(Input);
        }
    }
}

src/MoneyTrack.V3/Pages/Records/Edit.cshtml.cs
using CloudyWing.MoneyTrack.Infrastructure.Filters;
using CloudyWing.MoneyTrack.Infrastructure.Util;
using CloudyWing.MoneyTrack.Models.Application;
using CloudyWing.MoneyTrack.Pages.Records.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CloudyWing.MoneyTrack.Pages.Records {
    public class EditModel : PageModelBase {
        private readonly RecordEditAppService appService;

        public EditModel(RecordEditAppService appService) {
            ExceptionUtils.ThrowIfNull(() => appService);

            this.appService = appService;
        }

        public override string? MenuKey => "Records";

        [BindProperty]
        public EditInputModel? Input { get; set; }

        public IEnumerable<SelectListItem> Categories { get; set; }

        public async Task OnGetAsync(long? id) {
            Input = id.HasValue
                ? await appService.GetSingleAsync(id.Value)
                : new EditInputModel {
                    RecordDate = DateTime.Today,
                };
            await LoadCategoriesAsync();
        }

        [ValidationExecution(OnFailResultAction = nameof(LoadCategoriesAsync))]
        public async Task<ActionResult> OnPostAsync() {
            ApplicationResult result = await appService.SaveAsync(Input);
            if (result.IsError) {
                StatusNotification = new NotificationViewModel(result);
                return Page();
            }

            return RedirectToPage("./Index");
        }

        private async Task LoadCategoriesAsync() {
            Categories = await appService.GetCategoriesAsync();
        }
    }
}

src/MoneyTrack.V3/Pages/Categories/Edit.cshtml
@page
@model EditModel
@{
    Layout = "~/Pages/Shared/_FormLayout.cshtml";
}

@if (Model.Input.Id.HasValue) {
    <input type="hidden" asp-for="Input.Id" />
}
<div class="row mb-3">
    <label asp-for="Input!.Name" class="col-sm-3 ccol-md-2 col-form-label"></label>
    <div class="col-sm-9 ccol-md-10">
        <input asp-for="Input!.Name" type="search" class="form-control" />
        <span asp-validation-for="Input!.Name" class="text-danger"></span>
    </div>
</div>

@section Buttons {
    <button type="submit" form="editForm" formaction="@(Url.Action(Model.Input!.Id.HasValue ? "Update" : "Create"))" class="btn btn-primary">儲存</button>
    <a class="btn btn-info" asp-page="./Index">返回</a>
}

src/MoneyTrack.V3/Pages/Categories/Index.cshtml
@page
@using CloudyWing.MoneyTrack.Pages.Categories
@using CloudyWing.MoneyTrack.Pages.Categories.Models

@model IndexModel
@{
    Layout = "~/Pages/Shared/_QueryLayout.cshtml";
}

@section QueryFields {
    <div class="row mb-3">
        <label asp-for="Input!.Name" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input type="search" asp-for="Input!.Name" class="form-control" />
            <span asp-validation-for="Input!.Name" class="text-danger"></span>
        </div>
    </div>
}

@section QueryButtons {
    <button type="submit" class="btn btn-primary">查詢</button>
}

@section Buttons {
    <a asp-page="./Edit" class="btn btn-info">新增</a>
}

@if (Model.Records?.Any() == true) {
    int index = 0;
    int count = Model.Records.Count();
    <table class="table table-striped table-bordered table-hover">
        <tr>
            <th>
                @(Html.DisplayNameFor(m => Model.Records.First().Name))
            </th>
            <th></th>
        </tr>
        @foreach (IndexRecordModel record in Model.Records) {
            <tr>
                <td>
                    @Html.DisplayFor(m => record.Name)
                </td>
                <td>
                    <a class="btn btn-info" asp-page="Edit" asp-route-id="@record.Id">編輯</a>
                    @if (record.RecordCount > 0) {
                        <button type="button" class="btn btn-danger disabled">刪除</button>
                    } else {
                        <button type="submit" class="btn btn-danger" v-confirm.delete asp-page-handler="Delete" asp-route-id="@record.Id">刪除</button>
                    }
                    @if (index > 0) {
                        <button type="submit" class="btn btn-secondary" asp-page-handler="MoveUp" asp-route-id="@record.Id">上移</button>
                    } else {
                        <button type="button" class="btn btn-secondary disabled">上移</button>
                    }
                    @if (index < count - 1) {
                        <button type="submit" class="btn btn-secondary" asp-page-handler="MoveDown" asp-route-id="@record.Id">下移</button>
                    } else {
                        <button type="button" class="btn btn-secondary disabled">下移</button>
                    }
                </td>
            </tr>
            index++;
        }
    </table>
} else {
    <partial name="_EmptyDataMessage" />
}